Week1/programming paradigm
zzolab/Computer_Science_Study pull request #12
Opened 2022-09-21 06:12 UTC by Ridealist

- 내용 수정 및 사진 첨부

2022-09-22 04:35 UTC, sendmethere approved these changes
확인했습니다. 👍

2022-09-22 14:39 UTC, hoetaek approved these changes
오~ C까지?? 다음주 발표 기대됩니다!

2022-09-27 12:28 UTC, Szzng approved these changes
열정을 갈아넣은 문서 감사합니다 꼭 다시 읽어보겠습니다

2022-09-27 12:28 UTC, Szzng commented on 프로그래밍패러다임/선언형과_함수형_프로그래밍.md
> + - 프로그래밍 언어나 방식을 배우는 것이 하닌, 함수로 프로그래밍하는 사고를 배우는 것
하닌 -> 아닌 ㅎ

2022-09-27 12:28 UTC, Szzng commented on 프로그래밍패러다임/객체지향_프로그래밍.md
> +        print("나이를 설정합니다.")
이름?

2022-09-27 12:28 UTC, Szzng commented on 프로그래밍패러다임/객체지향_프로그래밍.md
> +        print("나이를 변경합니다.")
이름?

2022-09-28 12:41 UTC, nerburiya approved these changes
각각의 패러다임이 필요한 부분을 활용해 혼합하는 수준이 되려면.. 수없이 많은 경험이 필요하겠죠 ㅠㅠ 
강의 잘 들었습니다! 긴 내용인데도 집중하면서 잘 들을 수 있었어요 감사합니다 ㅎㅎ

2022-09-28 12:41 UTC, nerburiya commented on 프로그래밍패러다임/선언형과_함수형_프로그래밍.md
> +
실제로 수학에서는 함수 공간이라고 해서 벡터 공간과 동일하게도 사용하는데 비슷한 것 같아요...! 그런 개념을 적용한게 아닐까 생각이 들었어요

2022-09-28 13:13 UTC, nlom0218 approved these changes
전 사실 지금까지 함수형, 객체지향 이런거 생각없이 코드를 작성 하였는데, 앞으론 생각이라는 것을 하며 구조를 쌓아봐야겠어요ㅋㅋㅋ 많은 내용 정리해주시느라 고생많으셨습니다!

정말 지금까진 그냥 이렇게 하는게 좋은데? 하면서 코테 코드도 작성하고 그랬네요ㅋㅋㅋ

2022-09-28 13:53 UTC, hoetaek requested changes

2022-09-28 13:53 UTC, hoetaek commented on 프로그래밍패러다임/선언형과_함수형_프로그래밍.md
> +strings.sort(key = lambda x: len(set(list(x))))
len(set(x)) 로 해도 충분한 거 같아요~

2022-09-28 14:17 UTC, Ridealist commented on 프로그래밍패러다임/객체지향_프로그래밍.md
> +        print("나이를 설정합니다.")
예제를 변형하면서 print 부분을 못바꿨었네요.

2022-09-28 14:19 UTC, Ridealist commented on 프로그래밍패러다임/선언형과_함수형_프로그래밍.md
> +
오 함수 공간이라는 것이 있군요... 한 번 찾아서 공부해봐야겠네요. 답변 감사합니다.ㅎㅎ

2022-09-28 14:21 UTC, Ridealist commented on 프로그래밍패러다임/선언형과_함수형_프로그래밍.md
> +strings.sort(key = lambda x: len(set(list(x))))
아 그러네 set("foo") 만으로도 {"f", "o"} 이렇게 집합이 생성되겠구먼. 땡스 회택!

2022-09-28 14:23 UTC, Ridealist commented
> 전 사실 지금까지 함수형, 객체지향 이런거 생각없이 코드를 작성 하였는데, 앞으론 생각이라는 것을 하며 구조를 쌓아봐야겠어요ㅋㅋㅋ 많은 내용 정리해주시느라 고생많으셨습니다!
> 
> 정말 지금까진 그냥 이렇게 하는게 좋은데? 하면서 코테 코드도 작성하고 그랬네요ㅋㅋㅋ 하지만 앞으로도 제 편한 방법으로 한다는것ㅎㅎ

생각하면서 코드 짜기가 정말 쉽지 않은 것 같아요ㅋㅋㅋㅋ 짜다보면 편한 방법대로 가게 되니까... 프로그래밍 패러다임은 사실 오랜 기간에 거쳐 발전해온 개념이니 만큼 코딩 경력이 많이 쌓여야 자연스럽게 그 필요성이 느껴지고, 그 때 비로서 그 패러다임을 온전히 구현해볼 동기부여가 되지 않을까 싶기도 해요...! 리뷰 감사해요 홍동쌤~~

2022-09-29 15:23 UTC, hoetaek approved these changes

2022-09-29 23:22 UTC, merged